---
- name: Join additional control plane
  block:
    - name: Create control plane join configuration
      ansible.builtin.template:
        src: join-control-plane.yaml.j2
        dest: /etc/kubeadm-join-control-plane.yaml
        owner: root
        group: root
        mode: "0600"
      no_log: true

    - name: Join control plane
      ansible.builtin.command:
        cmd: kubeadm join --config /etc/kubeadm-join-control-plane.yaml
        creates: /etc/kubernetes/admin.conf

  always:
    - name: Remove temporary join configuration
      ansible.builtin.file:
        path: /etc/kubeadm-join-control-plane.yaml
        state: absent

- name: Create platform kubeconfig directory
  ansible.builtin.file:
    path: /home/platform/.kube
    state: directory
    owner: platform
    group: platform
    mode: "0700"

- name: Install admin kubeconfig for platform
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/platform/.kube/config
    remote_src: true
    owner: platform
    group: platform
    mode: "0600"
