---
- name: Remove legacy Kubernetes repository definition
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Configure Kubernetes repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    types:
      - deb
    uris:
      - "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor_version }}/deb/"
    suites:
      - "/"
    architectures:
      - amd64
    signed_by: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor_version }}/deb/Release.key"
    state: present

- name: Update apt cache after Kubernetes repository configuration
  ansible.builtin.apt:
    update_cache: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - "kubelet={{ kubernetes_package_version }}"
      - "kubeadm={{ kubernetes_package_version }}"
      - "kubectl={{ kubernetes_package_version }}"
    state: present
    allow_downgrade: true
    allow_change_held_packages: true
    update_cache: true

- name: Configure crictl
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: "0644"

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    enabled: true

- name: Verify CRI
  ansible.builtin.command:
    cmd: crictl info
  changed_when: false
