---
- name: Join worker node
  block:
    - name: Create worker join configuration
      ansible.builtin.template:
        src: join-worker.yaml.j2
        dest: /etc/kubeadm-join-worker.yaml
        owner: root
        group: root
        mode: "0600"
      no_log: true

    - name: Join worker
      ansible.builtin.command:
        cmd: kubeadm join --config /etc/kubeadm-join-worker.yaml
        creates: /etc/kubernetes/kubelet.conf

  always:
    - name: Remove temporary worker join configuration
      ansible.builtin.file:
        path: /etc/kubeadm-join-worker.yaml
        state: absent

- name: Label worker node
  ansible.builtin.command:
    cmd: >-
      kubectl --kubeconfig=/etc/kubernetes/admin.conf
      label node {{ inventory_hostname }} node-role.kubernetes.io/worker= --overwrite
  delegate_to: "{{ primary_control_plane }}"
  changed_when: true